[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "crackpy"
authors = [
    {name = "Tobias Strohmann"},
    {name = "David Melching", email = "David.Melching@dlr.de"},
    {name = "Florian Paysan"},
    {name = "Ferdinand Dömling"},
    {name = "Eric Dietrich"},
    {name = "Eric Breitbarth", email = "Eric.Breitbarth@dlr.de"},
]
description = "Crack Analysis Tool in Python (CrackPy) - automatic detection and fracture mechanical analysis of (fatigue) cracks using digital image correlation"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["Fracture Analysis", "Crack Tip Detection", "Fatigue", "Digital Image Correlation"]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "matplotlib>=3.5.3",
    "numpy>=1.23.2",
    "opencv_python>=4.5.4.60",
    "pandas>=1.4.3",
    "pyvista>=0.46.0",
    "scikit_image>=0.19.3",
    "scikit_learn>=1.1.2",
    "scipy>=1.9.0",
    "torch>=1.13.1",
    "torchvision>=0.13.1",
    "rich>=12.5.1",
    "pyyaml>=6.0",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["."]
include = ["crackpy*"]
exclude = ["test_scripts*", "crackpy.tests*", "example_images*", "scripts*"]

[tool.setuptools.package-data]
crackpy = ["logging.yaml"]

[tool.setuptools.dynamic]
version = { attr = "crackpy.__version__" }

[project.urls]
Repository = "https://github.com/dlr-wf/crackpy"
Documentation = "https://github.com/dlr-wf/crackpy/wiki"
Issues = "https://github.com/dlr-wf/crackpy/issues"
